### ISSUE TITLE
Moving without maps crash

### ISSUE THREAD

**Issue by YouriRombouts** [ocdy1001/uu-uce#61]
Trying to move the camera when no layers are loaded in will cause a crash with error:
```java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 4.9E-324 is less than minimum 1.7976931348623157E308.
        at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1129)
        at com.uu_uce.shapefiles.Camera.setPos(Camera.kt:111)
        at com.uu_uce.shapefiles.Camera.updateSlide(Camera.kt:234)
        at com.uu_uce.shapefiles.Camera.update(Camera.kt:180)
        at com.uu_uce.views.CustomMap.onDraw(CustomMap.kt:140)```

**Comment by YouriRombouts** [comment]
Fixed in #64
